name: Banking Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 7900:7900 # VNC server for debugging
        options: --shm-size=2g
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create .env file
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "USERNAME=${{ secrets.TEST_USERNAME }}" >> .env
          echo "PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env
      
      - name: Run Tests
        run: |
          mkdir -p reports
          # Check which test directories exist and run tests accordingly
          if [ -d "tests/smoke" ]; then
            echo "Running smoke tests..."
            pytest tests/smoke --junitxml=reports/smoke.xml
          else
            echo "Smoke test directory not found, skipping..."
          fi
          
          if [ -d "tests/api" ]; then
            echo "Running API tests..."
            pytest tests/api --junitxml=reports/api.xml
          else
            echo "API test directory not found, skipping..."
          fi
          
          if [ -d "tests/ui" ]; then
            echo "Running UI tests..."
            pytest tests/ui --junitxml=reports/ui.xml
          else
            echo "UI test directory not found, skipping..."
          fi
          
          # Run general tests if specific directories don't exist
          if [ ! -d "tests/smoke" ] && [ ! -d "tests/api" ] && [ ! -d "tests/ui" ]; then
            echo "Running general tests..."
            pytest tests --junitxml=reports/general.xml
          fi
      
      - name: Generate Allure report
        if: always()
        continue-on-error: true
        run: |
          echo "Attempting to generate Allure report..."
          mkdir -p reports/allure
          pip install allure-pytest || echo "Failed to install allure-pytest, continuing..."
          pytest --alluredir=reports/allure || echo "Allure report generation failed, continuing..."
          echo "Report generation attempted"
      
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
